networks:
  # The presence of these objects is sufficient to define them
  expense: {}
volumes:
  mysql:
services:
#docker run -d -v mysql:/docker-entrypoint-initdb.d --netowrk=expense --name=mysql mysql
  mysql:
    image: mysql
    networks:
      - expense
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: backend:1.0.0
    command: sh -c "sleep 5 && node /app/index.js" 
    networks:
      - expense
    container_name: backend
    depends_on: 
      - mysql
  frontend:
    image: frontend:1.0.0
    networks: expense
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    